version: "3"
services:
  ssh-tunnel:
    image: solo5star/ssh-tunnel
    build: .
    restart: unless-stopped
    ports:
      - 22:22
    volumes:
      - ./ssh:/ssh
    environment:
      - TUNNEL_HOST=example.com
      - LOCAL_PORT=22
      - REMOTE_HOST=localhost
      - REMOTE_PORT=22
